### ISSUE TITLE
Zählerstand ended nicht bei 21 bzw. 30

### ISSUE THREAD

**Issue by toehold** [bnw/badminton-anzeige#1]
Hallo,

sollte der Zählerstand, wenn ein Team 21 Punkte erreicht hat nicht enden? Ebenso wenn eines der Teams 30 Punkte erreicht hat.

Vielen Dank

**Comment by bnw** [comment]
Hi,
ich habe damals überlegt, ob direkt ein neuer Satz losgehen sollte, wenn ein Spieler genug Punkte gemacht hat. Ich habe mich dagegen entschieden, da dies es schwieriger macht, einen Fehlklick zu korrigieren. 
Du hast Recht, man könnte einbauen, dass man keine Punkte über 30 eingeben kann. Aber das lohnt sich meiner Meinung nach nicht. Wenn der Benutzer falsche Werte eingibt, ist das Programm ohnehin machtlos. 
Falls du noch weitere Anmerkungen oder Vorschläge hast, kannst du das Issue gerne wieder öffnen. :)
Viele Grüße
